---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
source("../scripts/init.R", chdir=TRUE)
library(broom)
library(ggplot2)
library(forcats)
theme_set(theme_minimal())

plot_lm = function(m) {
  m %>% 
    broom::tidy() %>% 
    mutate(term=fct_reorder(term, estimate)) %>% 
    ggplot() + 
    geom_col(aes(y=term, x=estimate))
}

bank = load_("bank", data_dict = data_dict)
bank = select(bank, -bank, -receiver_iban) %>% filter(!is_self_payment(receiver, payer, name="rafael savvides"))
```

```{r}
plot_lm(lm(data=bank, formula=amount~type-1) )

bank %>% 
  group_by(type) %>% 
  summarize(amount=mean(amount), .groups = "drop") %>% 
  arrange(-amount)
```

```{r}
plot_lm(lm(data=bank, formula=amount~payer-1))

bank %>% 
  group_by(payer) %>% 
  summarize(amount=mean(amount)) %>% 
  arrange(amount)
```

The spike at 2.60 is from the school cafeterias.

```{r}
bank %>% 
  filter(payer == "RAFAEL SAVVIDES") %>% 
  ggplot() +
  geom_histogram(aes(x=-amount), bins=50) + 
  scale_x_log10()

bank %>% 
  filter(payer == "RAFAEL SAVVIDES") %>% 
  count(amount, sort=TRUE)
```

```{r}

plot_lm(lm(data=bank, formula=amount~type+payer-1))
```

