---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r init, message=FALSE}
library(tidyverse)
library(lubridate)
library(aggregator)

#' Find self payments 
#' A self payment is where the payer and receiver are the same.
#'
#' @param receiver 
#' @param payer 
#' @param name 
#'
#' @return logical
#' @export
#'
#' @examples
is_self_payment = function(receiver, payer, name) {
  r = tolower(receiver)
  p = tolower(payer)
  name = tolower(strsplit(name, " ")[[1]])
  grepl(name[1], r) & grepl(name[2], r) & grepl(name[1], p) & grepl(name[2], p)
}

theme_set(theme_minimal())
bank = aggregator::bank %>% 
  as_tibble() %>% 
  select(-receiver_iban) %>% 
  mutate(expense = ifelse(amount < 0, "expense", "income"), 
         amount = abs(amount)) %>% 
  filter(!is_self_payment(receiver, payer, "rafael savvides")) %>% 
  mutate(week = lubridate::week(date), 
         year = lubridate::year(date), 
         week = as.factor(week)) %>% 
  # Add implicit NAs, weeks with no events have amount=0.
  right_join(expand.grid(year=2017:2020, 
                         week=factor(1:53), 
                         expense=c("income", "expense")), 
             by=c("week", "year", "expense")) %>% 
  mutate(amount = ifelse(!is.na(amount), amount, 0)) %>% 
  group_by(week, year, expense) %>% 
  mutate(avg_amount = mean(amount), 
         tot_amount = sum(amount)) %>% 
  ungroup()

tags = read.csv("../data/transaction_tags.csv")
bank$tags = map_chr(str_to_lower(bank$receiver), get_tags, tags$name, tags$category)
```

```{r}
wolt_per_month = bank %>% 
  filter(str_detect(receiver, "Wolt")) %>% 
  group_by(year_month = floor_date(as.Date(date), "month")) %>% 
  summarise(total_wolt = -sum(amount), 
            num_wolt = length(amount)) 

fig_wolt = ggplot(wolt_per_month) + theme_minimal() + 
  geom_col(aes(year_month, total_wolt)) + 
  labs(x="", y="", title="Total spent in Wolt per month") + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b\n%Y")

fig_wolt
```


```{r}
boats_per_month = bank %>% 
  filter(
    str_detect(str_to_lower(receiver), "tallink|viking") |  
    str_detect(str_to_lower(message), "ecker")) %>% 
  group_by(year_month = floor_date(as.Date(date), "month")) %>% 
  summarise(total_boat = -sum(amount), 
            num_boat = length(amount)) 

fig_boats = ggplot(boats_per_month) + theme_minimal() + 
  geom_col(aes(year_month, total_boat)) + 
  labs(x="", 
       y="", 
       title="Total spent in ferry tickets per month", 
       subtitle="Tickets from Laevapiletid may not be included") + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b\n%Y")

fig_boats
```


```{r}
total_per_receiver = bank %>% 
  filter(amount < 0, 
         !str_detect(str_to_lower(receiver), "rafael savvides")) %>% 
  group_by(receiver, 
           year = year(as.Date(date))) %>% 
  summarise(total = -sum(amount), 
            n = n()) %>% 
  arrange(-total) %>% 
  ungroup()

total_per_receiver %>% 
  group_by(receiver) %>% 
  summarise(total=sum(total)) %>% 
  top_n(10, total) %>% 
  mutate(receiver = fct_reorder(receiver, total)) %>% 
  ggplot() + 
  geom_col(aes(total, receiver)) + 
  labs(x="Euros", 
       y="", 
       title="Where I spent the most")

total_per_receiver %>% 
  group_by(year) %>% 
  top_n(5, total) %>% 
  mutate(receiver = fct_reorder(receiver, total)) %>% 
  ggplot() + 
  geom_col(aes(total, receiver)) + 
  facet_wrap(~year, scales = "free_y") + 
  labs(x="Euros", 
       y="", 
       title="Where I spent the most per year")

total_per_receiver %>% 
  group_by(receiver) %>% 
  summarise(n=sum(n)) %>% 
  top_n(20, n) %>% 
  mutate(receiver = fct_reorder(receiver, n)) %>% 
  ggplot() + 
  geom_col(aes(n, receiver)) + 
  labs(x="#Transactions", 
       y="", 
       title="Most frequent transactions")

total_per_receiver %>% 
  group_by(year) %>% 
  top_n(5, n) %>% 
  ggplot() + 
  geom_col(aes(n, receiver)) + 
  facet_wrap(~year, scales = "free_y") + 
  labs(x="#Transactions", 
       y="", 
       title="Most frequent transactions per year")
```

```{r}
bank_savings = bank %>% 
  filter(receiver == "RAFAEL SAVVIDES", 
         str_detect(receiver_iban, "FI80"), 
         amount < 0) %>% 
  mutate(month = floor_date(as.Date(date), "month")) 
bank_savings %>% 
  # Remove initial amount
  filter(-amount < 5000) %>% 
  ggplot() + 
  geom_col(aes(month, -amount)) + 
  geom_smooth(aes(month, -amount), level=0) + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b\n%Y") + 
  scale_y_continuous(labels=scales::dollar_format(prefix="", suffix="e")) + 
  coord_cartesian(ylim=c(0, NA)) + 
  labs(x="", y="", title="Money saved per month")
```

```{r}
bank %>% 
  as_tibble() %>% 
  filter(!str_detect(str_to_lower(receiver), "savvides")) %>% 
  mutate(tags = str_remove(tags, "\\|.+")) %>% # Primary tag is first i.e. tag1|tag2|tag3.
  #separate_rows(tags, sep="\\|") %>% 
  mutate(tags = ifelse(tags == "", "other", tags)) %>% 
  group_by(tags, 
           date_floor = floor_date(as.Date(date), "month")) %>% 
  summarize(n = n(), 
            amount = -sum(amount)) %>% 
  ungroup() %>% 
  mutate(tags = fct_reorder(tags, amount, sum)) %>% 
  ggplot() + 
  geom_col(aes(x=date_floor, y = amount, fill = tags)) + 
  labs(x="", y="")
```

# Weekly


```{r}
bank %>% 
  mutate(expense = factor(expense, levels=c("income", "expense"))) %>% 
  ggplot() + 
  geom_col(aes(week, amount, fill=expense)) + 
  scale_x_discrete() + 
  facet_wrap(~year, ncol=1)
```

```{r}
bank  %>% 
  filter(expense=="expense") %>% 
  mutate(month = month(date, label=TRUE)) %>% 
  ggplot() + 
  geom_violin(aes(week, amount, fill=month)) + 
  scale_x_discrete() + 
  scale_y_log10(labels=scales::dollar_format(prefix="")) + 
  facet_wrap(~year, ncol=1)
```

