---
title: "Daylio"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


```{r}
library(aggregator)
library(ggplot2)
library(dplyr)

fig = daylio %>% 
  mutate(timestamp = as.POSIXct(timestamp), 
         activities = forcats::fct_reorder(activities, timestamp, length)) %>% 
  ggplot() + theme_minimal() + 
  geom_point(aes(x = timestamp, y=activities, color=mood), alpha=0.7) + 
  geom_vline(xintercept = as.POSIXct(c("2020-01-01", "2021-01-01")), lty=2, col="grey") + 
  scale_color_ordinal(name="Mood") + 
  scale_x_datetime(date_breaks = "1 month", date_labels = "%b\n%Y", name="") +
  labs(y="", title="Daylio activities", subtitle="Sorted by most frequent")

fig
```

```{r}

daylio |> 
  group_by(year = lubridate::year(timestamp)) |> 
  count(activities) |> 
  top_n(10) |> 
  mutate(activities = tidytext::reorder_within(activities, n, year)) |> 
  ggplot() + 
  geom_col(aes(n, activities)) + 
  facet_wrap(~year, scales="free_y")
```

