---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(aggregator)
library(tidyverse)

dota_matches |> 
  as_tibble()
```

# Winrate

By hero

```{r}
# Beta prior. Can fit empirical Bayes estimate with mle.
alpha0 = 1
beta0 = 1

winrates = dota_matches |> 
  select(hero, result) |> 
  group_by(hero) |> 
  summarize(wr = mean(result=="Won Match"), 
            n = n(), 
            n_wins = sum(result=="Won Match"), 
            .groups="drop") |> 
  # Shrink estimates with BetaBinomial
  mutate(alpha0 = alpha0, 
         beta0 = beta0, 
         alpha = alpha0 + n_wins, 
         beta = beta0 + n - n_wins, 
         wr_shrunk = alpha / (alpha + beta), 
         wr_low = qbeta(0.05, alpha, beta), 
         wr_high = qbeta(0.95, alpha, beta))
  
winrates |> 
  mutate(hero = fct_reorder(hero, wr)) |> 
  ggplot() + 
  geom_point(aes(wr, hero)) + 
  labs(y="", x="Winrate (naive)")

winrates |> 
  mutate(hero = fct_reorder(hero, wr_shrunk)) |> 
  ggplot() + 
  geom_point(aes(wr_shrunk, hero)) + 
  geom_errorbarh(aes(xmin=wr_low, xmax=wr_high, y=hero)) + 
  xlim(0,1) + 
  labs(y="", x="Winrate (shrunk)")
```

# Old analysis for data scraped with R

```{r}
library(tidyverse)
library(broom)
library(tidytext)
theme_set(theme_minimal())

#' Convert "03:02" to 3*60+2
#' hms_to_sec("03:02")
#' hms_to_sec("1:03:02")
hms_to_sec = function(x) {
  x_split = as.numeric(unlist(strsplit(x, ":")))
  if (length(x_split) == 3) 
    return(x_split[1]*3600 + x_split[2]*60 + x_split[3])
  if (length(x_split) == 2) 
    return(x_split[1]*60 + x_split[2])
}

dota = read_csv("dota_clean.csv", col_types = "cffDffciii")

dota_by_date = dota %>% 
  mutate(duration_sec = map_dbl(duration, hms_to_sec)) %>% 
  group_by(date) %>% 
  summarise(total_matches = n(), 
            total_hours = sum(duration_sec) / 3600) 

dota_by_date %>% 
  pivot_longer(c("total_matches", "total_hours"), names_to="metric") %>% 
  ggplot() + 
  geom_col(aes(date, value)) + 
  scale_x_date(date_breaks="2 months", date_labels = "%b\n%y") + 
  facet_wrap(~metric, scales = "free_y", ncol=1) + 
  labs(x="", y="")

#' Cumulative

dota_by_date %>% 
  arrange(date) %>% 
  mutate(cum_hours = cumsum(total_hours), 
         cum_matches = cumsum(total_matches)) %>% 
  pivot_longer(c("cum_matches", "cum_hours"), names_to="metric") %>% 
  ggplot() + 
  geom_col(aes(date, value)) + 
  scale_x_date(date_breaks="2 months", date_labels = "%b\n%y") + 
  facet_wrap(~metric, scales = "free_y", ncol=1) + 
  labs(x="", y="")

#' Fit a model
dota %>% 
  mutate(duration_min = map_dbl(duration, hms_to_sec)/60) %>% 
  lm(kills~hero + mode + skill_level + duration_min + result - 1, data=.) %>% 
  tidy() %>% 
  mutate(term = str_remove(term, "^hero"),
         term = fct_reorder(term, estimate)
  ) %>% 
  mutate(term_type = case_when(str_detect(term, "^mode") ~ "mode", 
                               str_detect(term, "^result") ~ "result", 
                               str_detect(term, "^skill") ~ "skill_level", 
                               TRUE ~ "other")) %>% 
  ggplot() + 
  geom_point(aes(y=term, x=estimate, color=term_type, shape=term_type)) + 
  geom_errorbarh(aes(xmin=estimate-std.error, xmax=estimate+std.error, y=term, color=term_type)) + 
  labs(x="", y="", title="kills~hero + mode + skill_level + duration_min (linear model coefficients)")

dota %>% 
  count(hero, mode) %>%
  add_count(mode, wt=n, name="n_mode") %>% 
  filter(n_mode > 20) %>% 
  mutate(hero = reorder_within(hero, n, mode)) %>% 
  ggplot() + 
  geom_col(aes(x=n, y=hero)) + 
  facet_wrap(~mode, scales = "free") + 
  scale_y_reordered() + 
  theme(axis.text.y = element_text(size=5)) + 
  labs(x="", y="", title="Most played heroes per game mode")

dota %>% 
  filter(mode=="All Pick") %>% 
  pivot_longer(c(kills, deaths, assists), names_to="score_name", values_to="score_value") %>% 
  group_by(score_name) %>% 
  #mutate(hero = fct_reorder(hero, score_value)) %>% 
  mutate(hero = reorder_within(hero, score_value, score_name)) %>% 
  ggplot() + 
  geom_boxplot(aes(y=hero, x=score_value)) + 
  facet_wrap(~score_name, scales = "free_y") + 
  scale_y_reordered() + 
  labs(x="", y="", title="KDA in All Pick")

```