---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(aggregator)
library(tidyverse)
library(lubridate)
theme_set(theme_minimal())
```

```{r}
facebook_chat
```
facebook number of messages per day ~ person + date + time of day? + tf-idf (message in day)

- subsampling due to some problems with Greek character encodings

```{r}
fb_by_day_person = facebook_chat |> 
  mutate(hour = hour(timestamp), 
         month = month(timestamp), 
         year = year(timestamp), 
         date = as.Date(timestamp), 
         val = 1, 
         sender = ifelse(sender=="", "Unknown", sender)) |> 
  slice(1:1000) |> 
  pivot_wider(c(timestamp, content, hour, month, date), names_from=sender, values_from=val, values_fill = 0) |> 
  add_count(date) |> 
  select(-timestamp, -content)

fb_by_day_person = facebook_chat |> 
  mutate(hour = as.factor(hour(timestamp)), 
         month = month.abb[month(timestamp)], 
         year = as.factor(year(timestamp)), 
         date = as.Date(timestamp), 
         sender = ifelse(sender=="", "Unknown", sender))  |> 
  add_count(date) |> 
  add_count(sender, name="n_sender") |> 
  filter(n_sender>30) |> 
  select(-chat_path, -timestamp, -media, -n_sender)
```

```{r}
fb_by_day_person |> 
  count(sender, sort=TRUE) |> 
  filter(n>30)
```


```{r}
fb_lm = fb_by_day_person |> 
  filter(year != "2009") |> 
  mutate(hour = fct_relevel(hour, "20"), 
         year = fct_relevel(year, "2015"), 
         month = fct_relevel(month, "Jan")) |> 
  lm(formula = n ~ hour + month + year)

fb_lm |> 
  broom::tidy(conf.int=TRUE) |> 
  filter(term != "(Intercept)") |> 
  mutate(term = fct_reorder(term, estimate)) |> 
  ggplot() + 
  geom_point(aes(estimate, term)) + 
  geom_errorbarh(aes(xmin=conf.low, xmax=conf.high, y=term)) + 
  geom_vline(aes(xintercept=0), lty=2) + 
  labs(x="#messages compared to Jan 2015 at 20:00 (?)", y="")
```

