---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


```{r}
library(broom)
library(ggplot2)
library(forcats)
library(dplyr)
library(tidyr)
library(lubridate)
library(stringr)
library(aggregator)
theme_set(theme_light())
```

```{r}
phone_recs = phone_recordings
phone_recs_notes = recordings_notes_phone

phone_recs_counts = phone_recs %>% 
  select(-abs_filename) %>% 
  mutate(hour = hour(timestamp), 
         minute = minute(timestamp), 
         year = year(timestamp), 
         month = month(timestamp)) %>% 
  add_count(year, month, hour, name="n_year_month_hour") %>% 
  # Add zeroes for missing times
  right_join(expand.grid(hour=0:23, month=1:12, year=min(.$year, na.rm=TRUE):max(.$year, na.rm=TRUE)), 
             by=c("hour", "year", "month")) %>% 
  mutate(n_year_month_hour = ifelse(is.na(n_year_month_hour), 0, n_year_month_hour))  %>% 
  left_join(phone_recs_notes, by=c("file"="filename"))
```

```{r}
phone_recs_counts %>% 
  mutate(hour=as.factor(hour), 
         year=as.factor(year), 
         month=as.factor(month)) %>% 
  glm(n_year_month_hour ~ hour + year + month - 1, data=., family ="poisson") %>% 
  tidy() %>% 
  mutate(term = str_remove(term, "year"), 
         term = fct_reorder(term, estimate)) %>% 
  ggplot() +  
  geom_point(aes(y=term, x=estimate)) + 
  geom_errorbarh(aes(xmin=estimate-std.error, xmax=estimate+std.error, y=term)) + 
  labs(x="", y="", title="Number of recordings")
  
```

```{r}
phone_recs_counts %>% 
  mutate(hour=as.factor(hour), 
         year=as.factor(year), 
         month=as.factor(month)) %>% 
  lm(rating ~ hour + year + month - 1, data=.) %>% 
  tidy() %>% 
  mutate(term = str_remove(term, "year"), 
         term = fct_reorder(term, estimate)) %>% 
  ggplot() +  
  geom_point(aes(y=term, x=estimate)) + 
  geom_errorbarh(aes(xmin=estimate-std.error, xmax=estimate+std.error, y=term)) + 
  labs(x="", y="", title="Rating")
```

