---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


```{r}
suppressPackageStartupMessages({
  library(aggregator)
  library(tidyverse)
  library(lubridate)
  library(plotly)
})
theme_set(theme_minimal())
#' Make implicit NAs explicit in date variable.
fill_date = function(df) {
  dates = tibble(date = seq(min(df$date), max(df$date), by=1))
  full_join(dates, df, by = "date") |> 
    arrange(date)
}
col_labels = c("other"="darkcyan", "laptop"="black", "laptop_work"="blue", "phone"="darkred", "sleep"="grey")

phone = app_usage |> 
  mutate(date = date(timestamp)) |> 
  filter(!str_detect(app, "Screen off"), 
         !str_detect(app, "Screen on"), 
         !(app=="Daylio" & duration > 3000), 
         duration < 10000) |> 
  group_by(date) |> 
  summarize(duration = sum(duration)) |> 
  mutate(activity = "phone")

laptop = activity_watch_afk |> 
  mutate(date = date(timestamp)) |> 
  filter(status == "not-afk") |> 
  group_by(date) |> 
  summarize(duration = sum(duration)) |> 
  mutate(activity = "laptop")

laptop_work = activity_watch_work_afk |> 
  mutate(date = date(timestamp)) |> 
  filter(status == "not-afk", date != "2019-01-01") |> 
  group_by(date) |> 
  summarize(duration = sum(duration)) |> 
  mutate(activity = "laptop_work")

screen_time = rbind(phone, laptop, laptop_work) |> 
  arrange(date) |> 
  fill_date() 

sleep = data.frame(date = seq(min(screen_time$date), max(screen_time$date), by=1), 
                   duration = 7.5*3600, 
                   activity = "sleep")

time_spent = screen_time |> 
  full_join(sleep) |> 
  mutate(duration = ifelse(is.na(duration), 0, duration / 3600))
leftover = time_spent |> 
  group_by(date) |> 
  summarize(duration = 24 - sum(duration), 
            activity = "other")
time_spent = time_spent |> 
  full_join(leftover) |> 
  mutate(activity = factor(activity, levels=names(col_labels)))


by_month = time_spent |> 
  group_by(year = year(date), 
           month = month(date), 
           activity) |> 
  summarize(duration = mean(duration), .groups = "drop")
```

```{r}
fig = time_spent |> 
  mutate(duration = round(duration, 2)) |> 
  ggplot() + 
  aes(x=date, y=duration) + 
  geom_col(aes(fill=activity)) + 
  scale_fill_manual(values=col_labels) + 
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20, 24)) + 
    scale_x_date(date_labels = "%Y %b", 
               date_breaks = "1 month", 
               name="") + 
  theme(axis.text.x = element_text(angle=90))
fig

ggplotly(fig)
```

```{r}
fig_monthly = by_month |> 
  mutate(date = date(paste0(year, "-", month, "-01")), 
         duration = duration) |> 
  ggplot() + 
  aes(x=date, y=duration) + 
  geom_col(aes(fill=activity)) +
  scale_fill_manual(values=col_labels) + 
  scale_x_date(date_labels = "%Y %b", 
               date_breaks = "1 month", name="") + 
  theme(axis.text.x = element_text(angle=90)) + 
  ylim(c(0, 24))


ggplotly(fig_monthly)
```

```{r}
time_spent |> 
  filter(activity != "sleep", !is.na(activity)) |> 
  ggplot() + 
  geom_histogram(aes(duration, fill=activity), bins = 50) + 
  scale_fill_manual(values=col_labels)+
  facet_wrap(~activity, scales = "free")
```

