---
title: "Predict Whatsapp sender with logistic regression"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
library(tidytext)
library(tibble)
library(broom)
library(ggplot2)

source("../scripts/init.R", chdir=T)
chats = load_("whatsapp", data_dict)
chats_small = chats#[sample(nrow(chats), 100), ]

chats_wide = chats_small %>% 
  mutate(message_id = rownames(.)) %>% 
  rename(message_sender = sender) %>% 
  unnest_tokens(word, message) %>% 
  anti_join(stop_words, 'word') %>% 
  add_count(word, name = 'n_tot') %>% 
  filter(n_tot > 20) %>% 
  mutate(n_in_msg = 1) %>% 
  group_by(timestamp, message_sender, message_id, word) %>% 
  summarise(n_in_msg = sum(n_in_msg), .groups = "drop") %>% 
  pivot_wider(c(message_id, timestamp, message_sender), 
              names_from=word, 
              values_from = n_in_msg, 
              values_fill = 0, 
              names_repair = "unique")
```

Train logistic regression to predict sender based on words in a message (takes few minutes).

```{r}
m = glm(message_sender~.-1, 
        family=binomial, 
        data=mutate(chats_wide[,-c(1,2)], message_sender=as.factor(message_sender)))
# Coefficients can be NA because of the dummy variable trap (multicolinearity).
# https://en.wikipedia.org/wiki/Dummy_variable_%28statistics%29
```

```{r}
m_estimates = tidy(m) %>% 
  filter(!is.na(estimate))  %>% 
  # Keep only estimates that don't overlap with zero.
  filter(((estimate + std.error) < -0.2) | (estimate - std.error) > 0.2) %>% 
  mutate(term = forcats::fct_reorder(term, estimate), 
         ) 

fig = m_estimates %>% 
  ggplot() + 
  theme_light() + 
  geom_point(aes(y=term, x=estimate)) + 
  geom_errorbarh(aes(y=term, 
                     xmin=estimate-std.error, 
                     xmax=estimate+std.error)) + 
  geom_vline(aes(xintercept=0), lty=2, col="darkgrey") + 
  theme(axis.text.y = element_text(size=5), 
        panel.grid.minor = element_blank()) + 
  labs(y="", x="Estimate", title="Logistic regression coefficients for predicting Whatsapp message sender", 
       subtitle="for words that appear over 20 times, and have coefficients > 0.2") 
      
fig  
```
```{r}
# plotly::ggplotly(fig)
ggsave("whatsapp.pdf", fig, width=9, height=13)
```


