---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


```{r}
library(aggregator)
```

```{r}
tasks_by_word = work_diary_tasks %>% 
  filter(value != "") %>% 
  mutate(value = str_to_lower(value)) %>% 
  separate_rows(value) 
```


```{r}
tasks_by_word %>% 
  group_by(time) %>% 
  count(value, sort=TRUE)
```
```{r}
tasks_by_word %>% 
  group_by(date) %>% 
  count(value, sort=TRUE)
```


# 2022-01-05



```{r}
make_ts = function(ymd, hm) strptime(paste(ymd, hm), format="%F %H:%M", tz="Europe/Helsinki")
add_hours = function(ts, h) ts + 3600 * h
hour_min2sec = function(hm) {s = as.integer(strsplit(hm, ":")[[1]]); s[1]*3600 + s[2]*60}
work_diary_tasks2 = work_diary_tasks |> 
  rename(event=value, start=time) |> 
  filter(event != "", 
         substr(date, 1, 4) != "2019") |> 
  inner_join(work_diary_hours[,c("date", "finish", "extra")], by="date") |> 
  rename(max_finish = finish) |> 
  mutate(max_finish = make_ts(date, max_finish), 
         start = make_ts(date, start),
         duration_in_text = as.integer(gsub("\\.|h", "", str_extract(event, "\\d(\\.\\d)?h"))), 
         start_plus_duration = add_hours(start, duration_in_text), 
         extra_sec = sapply(extra, hour_min2sec)
         ) |> 
  group_by(date) |> 
  mutate(next_start = lead(start)) |> 
  ungroup() |> 
  mutate(finish = ifelse(!is.na(start), pmin(next_start, max_finish, start_plus_duration, na.rm = TRUE), NA),
         finish = as.POSIXct(finish, origin="1970-01-01")) |> 
  mutate(duration_sec = ifelse(!is.na(start), finish - start, extra_sec)) |> 
  select(date, event, start, finish, duration_sec)
```

```{r}
hrs_per_project = work_diary_tasks2 |> 
  mutate(project = tolower(gsub("#", "", str_extract(event, "\\#\\w+\\b")))) |> 
  filter(!is.na(project)) |> 
  group_by(project) |> 
  summarize(total_hrs = sum(duration_sec, na.rm = TRUE)/3600)

library(ggplot2)
library(forcats)
hrs_per_project |> 
  mutate(project = fct_reorder(project, total_hrs)) |> 
  ggplot() + theme_minimal() + 
  geom_col(aes(total_hrs, project)) + 
  geom_text(aes(x=0, y=project, label=round(total_hrs)), hjust=1.2, size=2.5) + 
  labs(title="Hours spent per project in 2020-2021", x="Hours", y="")

```

