---
title: "R Notebook"
date: 2019-12-31
output: html_notebook
editor_options: 
  chunk_output_type: console
---


```{r}
library(dplyr)
library(tidyr)
library(stringr)
library(lubridate)
library(forcats)
library(ggplot2)
library(broom)
library(aggregator)
theme_set(theme_light())
```

```{r}
channel_first_view = youtube_history %>%
  group_by(channel) %>%
  summarise(first_view_of_channel = min(time))

youtube_history = youtube_history %>% 
  left_join(channel_first_view, by="channel")
```


# Most watched channels

```{r}
youtube_history %>% 
  count(channel, first_view_of_channel, channel_unique_videos, sort=T, name="channel_views")
```

# Number of videos per day

```{r}
youtube_history %>% 
  count(day = as.Date(time)) %>% 
  ggplot() + 
  geom_col(aes(day, n)) + 
  labs(title="Number of videos per day", x="", y="")
```

# Days with most videos watched

```{r}
youtube_history %>% 
  count(day = as.Date(time), sort=T) 
#TODO Fix NA dates
```

# Which times in the day are videos watched most?

```{r}
#TODO put mean/median instead of total number of videos
youtube_history %>% 
  count(hour = hour(time), sort=T) %>% 
  ggplot() + 
  geom_col(aes(hour, n)) + 
  labs(x = "Hour of day", y = "# of videos watched")
```

```{r}
#TODO put mean/median instead of total number of videos
youtube_history %>% 
  count(weekday = wday(time, label=TRUE), sort=T) %>% 
  ggplot() + 
  geom_col(aes(weekday, n)) + 
  labs(x = "", y = "# of videos watched")
```


```{r}
youtube_day_hour = youtube_history %>% 
  count(hour = hour(time), date = as.Date(time), sort=T) %>% 
  full_join(expand.grid(hour = 0:23, date = unique(as.Date(youtube_history$time)), n = 0), by = c("hour", "date")) %>% # Add days where no videos were watched.
  mutate(n = ifelse(!is.na(n.x), n.x, n.y)) %>% 
  select(hour, date, n) 

youtube_day_hour %>% 
  group_by(hour) %>% 
  summarise(avg_videos = mean(n), 
            median_videos = median(n), 
            max_videos = max(n), 
            geom_median_videos = exp(mean(log(n)))) %>% 
  ggplot + 
  geom_col(aes(x = hour, y = avg_videos))+ 
  labs(x = "Hour of day", "# of videos watched (average over days)")

youtube_day_hour %>% 
  mutate(hour = as.factor(hour)) %>% 
  ggplot() + 
  geom_boxplot(aes(hour, n)) + 
  labs(x = "Hour of day", "# of videos watched")
#TODO Can I somehow deal with the large number of zeros?
```


# Modeling

```{r}
videos_per_day =  youtube_history %>% 
  mutate(date = as_date(time), 
         channel = as.factor(channel)) %>% 
  add_count(date, name="n_videos") %>% 
  select(date, channel, n_videos)

# youtube_glm = glm(n_videos ~ 0 + channel, data=videos_per_day[1:1000, ], family = "poisson") # Too slow
youtube_glm = glm(n_videos ~ 0 + channel, data=videos_per_day[1:1000, ])

youtube_glm %>% 
  tidy() %>% 
  mutate(term = str_remove(term, "^channel"), 
         term = substr(term, 1, 15), 
         term = fct_reorder(term, estimate)) %>% 
  ggplot() + 
  geom_point(aes(estimate, term)) + 
  geom_errorbarh(aes(y=term, xmin=estimate-std.error, xmax=estimate+std.error))
  
  
```

